# generated by datamodel-codegen:
#   filename:  latest.json

from __future__ import annotations

from datetime import date, datetime
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field


class ErrorResponse(BaseModel):
    error: bool = Field(
        ...,
        description="Indica se a requisição resultou em erro. Sempre `true` para este schema.",
        example=True,
    )
    message: str = Field(..., description="Mensagem descritiva do erro ocorrido.")


class AvailableTickersResponse(BaseModel):
    indexes: list[str] = Field(
        ...,
        description="Lista de tickers de **índices** disponíveis (ex: `^BVSP`, `^IFIX`).",
    )
    stocks: list[str] = Field(
        ...,
        description="Lista de tickers de **ações, FIIs, BDRs e ETFs** disponíveis (ex: `PETR4`, `VALE3`, `MXRF11`).",
    )


class IndexSummary(BaseModel):
    stock: Optional[str] = Field(None, description="Ticker do índice (ex: `^BVSP`).")
    name: Optional[str] = Field(None, description="Nome do índice (ex: `IBOVESPA`).")


class StockSummary(BaseModel):
    stock: Optional[str] = Field(
        None, description="Ticker do ativo (ex: `PETR4`, `MXRF11`)."
    )
    name: Optional[str] = Field(
        None, description="Nome do ativo ou empresa (ex: `PETROBRAS PN`)."
    )
    close: Optional[float] = Field(
        None, description="Preço de fechamento mais recente ou último preço negociado."
    )
    change: Optional[float] = Field(
        None,
        description="Variação percentual do preço em relação ao fechamento anterior.",
    )
    volume: Optional[int] = Field(
        None, description="Volume financeiro negociado no último pregão ou dia atual."
    )
    market_cap: Optional[float] = Field(
        None,
        description="Capitalização de mercado (Preço x Quantidade de Ações). Pode ser nulo para FIIs ou outros tipos.",
    )
    logo: Optional[str] = Field(
        None, description="URL para a imagem do logo da empresa/ativo."
    )
    sector: Optional[str] = Field(
        None,
        description="Setor de atuação da empresa (ex: `Energy Minerals`, `Finance`). Pode ser nulo ou variar para FIIs.",
    )
    type: Optional[Literal["stock", "fund", "bdr"]] = Field(
        None,
        description="Tipo do ativo: `stock` (Ação), `fund` (Fundo Imobiliário/FII), `bdr` (Brazilian Depositary Receipt).",
    )


class QuoteListResponse(BaseModel):
    indexes: Optional[list[IndexSummary]] = Field(
        None,
        description="Lista resumida de índices relevantes (geralmente inclui IBOVESPA).",
    )
    stocks: Optional[list[StockSummary]] = Field(
        None, description="Lista paginada e filtrada dos ativos solicitados."
    )
    available_sectors: Optional[list[str]] = Field(
        None,
        alias="availableSectors",
        description="Lista de todos os setores disponíveis que podem ser usados no parâmetro de filtro `sector`.",
    )
    available_stock_types: Optional[list[Literal["stock", "fund", "bdr"]]] = Field(
        None,
        alias="availableStockTypes",
        description="Lista dos tipos de ativos (`stock`, `fund`, `bdr`) disponíveis que podem ser usados no parâmetro de filtro `type`.",
    )
    current_page: Optional[int] = Field(
        None,
        alias="currentPage",
        description="Número da página atual retornada nos resultados.",
    )
    total_pages: Optional[int] = Field(
        None,
        alias="totalPages",
        description="Número total de páginas existentes para a consulta/filtros aplicados.",
    )
    items_per_page: Optional[int] = Field(
        None,
        alias="itemsPerPage",
        description="Número de itens (ativos) retornados por página (conforme `limit` ou padrão).",
    )
    total_count: Optional[int] = Field(
        None,
        alias="totalCount",
        description="Número total de ativos encontrados que correspondem aos filtros aplicados (sem considerar a paginação).",
    )
    has_next_page: Optional[bool] = Field(
        None,
        alias="hasNextPage",
        description="Indica se existe uma próxima página de resultados (`true`) ou se esta é a última página (`false`).",
    )


class HistoricalDataPrice(BaseModel):
    date: Optional[int] = Field(
        None,
        description="Data do pregão ou do ponto de dados, representada como um timestamp UNIX (número de segundos desde 1970-01-01 UTC).",
    )
    open: Optional[float] = Field(
        None,
        description="Preço de abertura do ativo no intervalo (dia, semana, mês, etc.).",
    )
    high: Optional[float] = Field(
        None, description="Preço máximo atingido pelo ativo no intervalo."
    )
    low: Optional[float] = Field(
        None, description="Preço mínimo atingido pelo ativo no intervalo."
    )
    close: Optional[float] = Field(
        None, description="Preço de fechamento do ativo no intervalo."
    )
    volume: Optional[int] = Field(
        None, description="Volume financeiro negociado no intervalo."
    )
    adjusted_close: Optional[float] = Field(
        None,
        alias="adjustedClose",
        description="Preço de fechamento ajustado para proventos (dividendos, JCP, bonificações, etc.) e desdobramentos/grupamentos.",
    )


class CashDividend(BaseModel):
    asset_issued: Optional[str] = Field(
        None,
        alias="assetIssued",
        description="Ticker do ativo que pagou o provento (ex: `ITSA4`). Pode incluir sufixos específicos relacionados ao evento.",
    )
    payment_date: Optional[datetime] = Field(
        None,
        alias="paymentDate",
        description="Data efetiva em que o pagamento foi realizado (ou está previsto). Formato ISO 8601.",
    )
    rate: Optional[float] = Field(
        None,
        description="Valor bruto do provento pago por unidade do ativo (por ação, por cota).",
    )
    related_to: Optional[str] = Field(
        None,
        alias="relatedTo",
        description="Descrição do período ou evento ao qual o provento se refere (ex: `1º Trimestre/2023`, `Resultado 2022`).",
    )
    approved_on: Optional[datetime] = Field(
        None,
        alias="approvedOn",
        description="Data em que o pagamento do provento foi aprovado pela empresa. Pode ser uma estimativa em alguns casos. Formato ISO 8601.",
    )
    isin_code: Optional[str] = Field(
        None,
        alias="isinCode",
        description="Código ISIN (International Securities Identification Number) do ativo relacionado ao provento.",
    )
    label: Optional[str] = Field(
        None,
        description="Tipo do provento em dinheiro. Geralmente `DIVIDENDO` ou `JCP` (Juros sobre Capital Próprio).",
    )
    last_date_prior: Optional[datetime] = Field(
        None,
        alias="lastDatePrior",
        description="Data Com (Ex-Date). Último dia em que era necessário possuir o ativo para ter direito a receber este provento. Pode ser uma estimativa. Formato ISO 8601.",
    )
    remarks: Optional[str] = Field(
        None,
        description="Observações adicionais ou informações relevantes sobre o provento.",
    )


class StockDividend(BaseModel):
    asset_issued: Optional[str] = Field(
        None, alias="assetIssued", description="Ticker do ativo afetado pelo evento."
    )
    factor: Optional[float] = Field(
        None,
        description="Fator numérico do evento. \n* **Bonificação:** Percentual (ex: 0.1 para 10%).\n* **Desdobramento/Grupamento:** Fator multiplicativo ou divisor.",
    )
    complete_factor: Optional[str] = Field(
        None,
        alias="completeFactor",
        description="Descrição textual do fator (ex: `1 / 10`, `10 / 1`).",
    )
    approved_on: Optional[datetime] = Field(
        None,
        alias="approvedOn",
        description="Data em que o evento foi aprovado. Formato ISO 8601.",
    )
    isin_code: Optional[str] = Field(
        None, alias="isinCode", description="Código ISIN do ativo."
    )
    label: Optional[str] = Field(
        None,
        description="Tipo do evento: `DESDOBRAMENTO`, `GRUPAMENTO`, `BONIFICACAO`.",
    )
    last_date_prior: Optional[datetime] = Field(
        None,
        alias="lastDatePrior",
        description="Data Com (Ex-Date). Último dia para possuir o ativo nas condições antigas. Formato ISO 8601.",
    )
    remarks: Optional[str] = Field(
        None, description="Observações adicionais sobre o evento."
    )


class DividendsData(BaseModel):
    cash_dividends: Optional[list[CashDividend]] = Field(
        None,
        alias="cashDividends",
        description="Lista de proventos pagos em dinheiro (Dividendos e JCP).",
    )
    stock_dividends: Optional[list[StockDividend]] = Field(
        None,
        alias="stockDividends",
        description="Lista de eventos corporativos (Desdobramento, Grupamento, Bonificação).",
    )
    subscriptions: Optional[list[dict[str, Any]]] = Field(
        None,
        description="Lista de eventos de subscrição de ações (estrutura não detalhada aqui).",
    )


class SummaryProfile(BaseModel):
    address1: Optional[str] = Field(
        None, description="Linha 1 do endereço da sede da empresa."
    )
    address2: Optional[str] = Field(
        None, description="Linha 2 do endereço da sede da empresa (complemento)."
    )
    city: Optional[str] = Field(None, description="Cidade da sede da empresa.")
    state: Optional[str] = Field(
        None, description="Estado ou província da sede da empresa."
    )
    zip: Optional[str] = Field(
        None, description="Código Postal (CEP) da sede da empresa."
    )
    country: Optional[str] = Field(None, description="País da sede da empresa.")
    phone: Optional[str] = Field(
        None, description="Número de telefone principal da empresa."
    )
    website: Optional[str] = Field(
        None, description="URL do website oficial da empresa."
    )
    industry: Optional[str] = Field(
        None, description="Nome da indústria em que a empresa atua."
    )
    industry_key: Optional[str] = Field(
        None,
        alias="industryKey",
        description="Chave interna ou código para a indústria.",
    )
    industry_disp: Optional[str] = Field(
        None,
        alias="industryDisp",
        description="Nome de exibição formatado para a indústria.",
    )
    sector: Optional[str] = Field(
        None, description="Nome do setor de atuação da empresa."
    )
    sector_key: Optional[str] = Field(
        None, alias="sectorKey", description="Chave interna ou código para o setor."
    )
    sector_disp: Optional[str] = Field(
        None, alias="sectorDisp", description="Nome de exibição formatado para o setor."
    )
    long_business_summary: Optional[str] = Field(
        None,
        alias="longBusinessSummary",
        description="Descrição longa e detalhada sobre as atividades e o negócio da empresa.",
    )
    full_time_employees: Optional[int] = Field(
        None,
        alias="fullTimeEmployees",
        description="Número estimado de funcionários em tempo integral.",
    )
    company_officers: Optional[list[dict[str, Any]]] = Field(
        None,
        alias="companyOfficers",
        description="Lista de diretores e executivos principais da empresa (estrutura interna do objeto não detalhada aqui).",
    )


class BalanceSheetEntry(BaseModel):
    symbol: Optional[str] = Field(
        None, description="Ticker do ativo ao qual o balanço se refere."
    )
    type: Optional[Literal["yearly", "quarterly"]] = Field(
        None,
        description="Indica a periodicidade do balanço: `yearly` (anual) ou `quarterly` (trimestral).",
    )
    end_date: Optional[date] = Field(
        None,
        alias="endDate",
        description="Data de término do período fiscal ao qual o balanço se refere (YYYY-MM-DD).",
    )
    cash: Optional[float] = Field(None, description="Caixa e equivalentes de caixa.")
    short_term_investments: Optional[float] = Field(
        None,
        alias="shortTermInvestments",
        description="Aplicações financeiras de curto prazo.",
    )
    net_receivables: Optional[float] = Field(
        None,
        alias="netReceivables",
        description="Contas a receber líquidas (clientes).",
    )
    inventory: Optional[float] = Field(None, description="Estoques.")
    other_current_assets: Optional[float] = Field(
        None, alias="otherCurrentAssets", description="Outros ativos circulantes."
    )
    total_current_assets: Optional[float] = Field(
        None, alias="totalCurrentAssets", description="Total do ativo circulante."
    )
    long_term_investments: Optional[float] = Field(
        None, alias="longTermInvestments", description="Investimentos de longo prazo."
    )
    property_plant_equipment: Optional[float] = Field(
        None,
        alias="propertyPlantEquipment",
        description="Imobilizado (propriedades, instalações e equipamentos).",
    )
    other_assets: Optional[float] = Field(
        None, alias="otherAssets", description="Outros ativos não circulantes."
    )
    total_assets: Optional[float] = Field(
        None, alias="totalAssets", description="Total do ativo."
    )
    accounts_payable: Optional[float] = Field(
        None, alias="accountsPayable", description="Contas a pagar (fornecedores)."
    )
    short_long_term_debt: Optional[float] = Field(
        None,
        alias="shortLongTermDebt",
        description="Dívida de curto prazo (empréstimos e financiamentos circulantes).",
    )
    other_current_liab: Optional[float] = Field(
        None, alias="otherCurrentLiab", description="Outros passivos circulantes."
    )
    long_term_debt: Optional[float] = Field(
        None,
        alias="longTermDebt",
        description="Dívida de longo prazo (empréstimos e financiamentos não circulantes).",
    )
    other_liab: Optional[float] = Field(
        None, alias="otherLiab", description="Outros passivos não circulantes."
    )
    total_current_liabilities: Optional[float] = Field(
        None,
        alias="totalCurrentLiabilities",
        description="Total do passivo circulante.",
    )
    total_liab: Optional[float] = Field(
        None,
        alias="totalLiab",
        description="Total do passivo (circulante + não circulante).",
    )
    common_stock: Optional[float] = Field(
        None, alias="commonStock", description="Capital social realizado."
    )
    retained_earnings: Optional[float] = Field(
        None, alias="retainedEarnings", description="Lucros/Prejuízos acumulados."
    )
    treasury_stock: Optional[float] = Field(
        None, alias="treasuryStock", description="Ações em tesouraria."
    )
    other_stockholder_equity: Optional[float] = Field(
        None,
        alias="otherStockholderEquity",
        description="Outros componentes do patrimônio líquido.",
    )
    total_stockholder_equity: Optional[float] = Field(
        None, alias="totalStockholderEquity", description="Total do patrimônio líquido."
    )
    net_tangible_assets: Optional[float] = Field(
        None,
        alias="netTangibleAssets",
        description="Ativos tangíveis líquidos (Ativo Total - Intangíveis - Passivo Total).",
    )
    good_will: Optional[float] = Field(
        None,
        alias="goodWill",
        description="Ágio por expectativa de rentabilidade futura (Goodwill).",
    )
    intangible_assets: Optional[float] = Field(
        None,
        alias="intangibleAssets",
        description="Ativos intangíveis (marcas, patentes, etc.).",
    )
    deferred_long_term_asset_charges: Optional[float] = Field(
        None,
        alias="deferredLongTermAssetCharges",
        description="Encargos diferidos de ativos de longo prazo.",
    )
    deferred_long_term_liab: Optional[float] = Field(
        None,
        alias="deferredLongTermLiab",
        description="Passivos fiscais diferidos (longo prazo).",
    )
    minority_interest: Optional[float] = Field(
        None,
        alias="minorityInterest",
        description="Participação de não controladores (no patrimônio líquido).",
    )
    capital_surplus: Optional[float] = Field(
        None, alias="capitalSurplus", description="Reservas de capital."
    )
    taxes_to_recover: Optional[float] = Field(
        None, alias="taxesToRecover", description="Impostos a recuperar."
    )
    long_term_assets: Optional[float] = Field(
        None,
        alias="longTermAssets",
        description="Total do ativo não circulante (agregado).",
    )
    long_term_realizable_assets: Optional[float] = Field(
        None,
        alias="longTermRealizableAssets",
        description="Ativo realizável a longo prazo.",
    )
    long_term_receivables: Optional[float] = Field(
        None,
        alias="longTermReceivables",
        description="Contas a receber de longo prazo.",
    )
    long_term_deferred_taxes: Optional[float] = Field(
        None,
        alias="longTermDeferredTaxes",
        description="Tributos diferidos (Ativo Não Circulante).",
    )
    other_non_current_assets: Optional[float] = Field(
        None,
        alias="otherNonCurrentAssets",
        description="Outros ativos não circulantes (detalhamento).",
    )
    non_current_assets: Optional[float] = Field(
        None,
        alias="nonCurrentAssets",
        description="Total do ativo não circulante (sinônimo de `longTermAssets`).",
    )
    provisions: Optional[float] = Field(None, description="Provisões (passivo).")
    shareholders_equity: Optional[float] = Field(
        None,
        alias="shareholdersEquity",
        description="Patrimônio líquido (sinônimo de `totalStockholderEquity`).",
    )
    realized_share_capital: Optional[float] = Field(
        None,
        alias="realizedShareCapital",
        description="Capital social realizado (sinônimo de `commonStock`).",
    )
    capital_reserves: Optional[float] = Field(
        None,
        alias="capitalReserves",
        description="Reservas de capital (sinônimo de `capitalSurplus`).",
    )
    profit_reserves: Optional[float] = Field(
        None, alias="profitReserves", description="Reservas de lucros."
    )
    other_comprehensive_results: Optional[float] = Field(
        None,
        alias="otherComprehensiveResults",
        description="Outros resultados abrangentes.",
    )
    current_liabilities: Optional[float] = Field(
        None,
        alias="currentLiabilities",
        description="Total do passivo circulante (sinônimo de `totalCurrentLiabilities`).",
    )
    social_and_labor_obligations: Optional[float] = Field(
        None,
        alias="socialAndLaborObligations",
        description="Obrigações sociais e trabalhistas.",
    )
    providers: Optional[float] = Field(
        None, description="Fornecedores (sinônimo de `accountsPayable`)."
    )
    tax_obligations: Optional[float] = Field(
        None,
        alias="taxObligations",
        description="Obrigações fiscais (passivo circulante).",
    )
    loans_and_financing: Optional[float] = Field(
        None,
        alias="loansAndFinancing",
        description="Empréstimos e financiamentos (circulante).",
    )
    lease_financing: Optional[float] = Field(
        None,
        alias="leaseFinancing",
        description="Financiamento por arrendamento mercantil (circulante).",
    )
    other_obligations: Optional[float] = Field(
        None, alias="otherObligations", description="Outras obrigações (circulante)."
    )
    other_current_liabilities: Optional[float] = Field(
        None,
        alias="otherCurrentLiabilities",
        description="Outros passivos circulantes (sinônimo de `otherCurrentLiab`).",
    )
    non_current_liabilities: Optional[float] = Field(
        None,
        alias="nonCurrentLiabilities",
        description="Total do passivo não circulante.",
    )
    long_term_loans_and_financing: Optional[float] = Field(
        None,
        alias="longTermLoansAndFinancing",
        description="Empréstimos e financiamentos (não circulante).",
    )
    long_term_lease_financing: Optional[float] = Field(
        None,
        alias="longTermLeaseFinancing",
        description="Financiamento por arrendamento mercantil (não circulante).",
    )
    other_long_term_obligations: Optional[float] = Field(
        None,
        alias="otherLongTermObligations",
        description="Outras obrigações (passivo não circulante).",
    )
    long_term_provisions: Optional[float] = Field(
        None,
        alias="longTermProvisions",
        description="Provisões (passivo não circulante).",
    )
    updated_at: Optional[date] = Field(
        None,
        alias="updatedAt",
        description="Data da última atualização deste registro (YYYY-MM-DD).",
    )
    financial_assets: Optional[float] = Field(
        None,
        alias="financialAssets",
        description="Ativos financeiros (agregado de instrumentos financeiros no ativo).",
    )
    central_bank_compulsory_deposit: Optional[float] = Field(
        None,
        alias="centralBankCompulsoryDeposit",
        description="Depósitos compulsórios no Banco Central.",
    )
    financial_assets_measured_at_fair_value_through_profit_or_loss: Optional[float] = (
        Field(
            None,
            alias="financialAssetsMeasuredAtFairValueThroughProfitOrLoss",
            description="Ativos financeiros mensurados a valor justo por meio do resultado (FVTPL).",
        )
    )
    current_and_deferred_taxes: Optional[float] = Field(
        None,
        alias="currentAndDeferredTaxes",
        description="Tributos correntes e diferidos no ativo.",
    )
    investments: Optional[float] = Field(
        None, description="Investimentos (participações e outros)."
    )
    financial_assets_measured_at_fair_value_through_other_comprehensive_income: (
        Optional[float]
    ) = Field(
        None,
        alias="financialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome",
        description="Ativos financeiros mensurados a valor justo por outros resultados abrangentes (FVOCI).",
    )
    financial_assets_at_amortized_cost: Optional[float] = Field(
        None,
        alias="financialAssetsAtAmortizedCost",
        description="Ativos financeiros ao custo amortizado.",
    )
    accounts_receivable_from_clients: Optional[float] = Field(
        None,
        alias="accountsReceivableFromClients",
        description="Contas a receber de clientes (bruto).",
    )
    other_accounts_receivable: Optional[float] = Field(
        None, alias="otherAccountsReceivable", description="Outras contas a receber."
    )
    biological_assets: Optional[float] = Field(
        None, alias="biologicalAssets", description="Ativos biológicos."
    )
    prepaid_expenses: Optional[float] = Field(
        None, alias="prepaidExpenses", description="Despesas antecipadas."
    )
    long_term_accounts_receivable_from_clients: Optional[float] = Field(
        None,
        alias="longTermAccountsReceivableFromClients",
        description="Contas a receber de clientes - longo prazo.",
    )
    long_term_inventory: Optional[float] = Field(
        None, alias="longTermInventory", description="Estoques de longo prazo."
    )
    long_term_biological_assets: Optional[float] = Field(
        None,
        alias="longTermBiologicalAssets",
        description="Ativos biológicos de longo prazo.",
    )
    long_term_prepaid_expenses: Optional[float] = Field(
        None,
        alias="longTermPrepaidExpenses",
        description="Despesas antecipadas de longo prazo.",
    )
    credits_with_related_parties: Optional[float] = Field(
        None,
        alias="creditsWithRelatedParties",
        description="Créditos com partes relacionadas.",
    )
    shareholdings: Optional[float] = Field(
        None, description="Participações societárias."
    )
    investment_properties: Optional[float] = Field(
        None,
        alias="investmentProperties",
        description="Propriedades para investimento.",
    )
    other_long_term_receivables: Optional[float] = Field(
        None,
        alias="otherLongTermReceivables",
        description="Outros créditos/recebíveis de longo prazo.",
    )
    credits_from_operations: Optional[float] = Field(
        None,
        alias="creditsFromOperations",
        description="Créditos oriundos de operações (instituições financeiras/seguradoras).",
    )
    securities_and_credits_receivable: Optional[float] = Field(
        None,
        alias="securitiesAndCreditsReceivable",
        description="Títulos e créditos a receber.",
    )
    other_values_and_assets: Optional[float] = Field(
        None, alias="otherValuesAndAssets", description="Outros valores e bens."
    )
    compulsory_loans_and_deposits: Optional[float] = Field(
        None,
        alias="compulsoryLoansAndDeposits",
        description="Empréstimos e depósitos compulsórios.",
    )
    deferred_selling_expenses: Optional[float] = Field(
        None,
        alias="deferredSellingExpenses",
        description="Despesas de comercialização diferidas.",
    )
    long_term_financial_investments_measured_at_fair_value_through_income: Optional[
        float
    ] = Field(
        None,
        alias="longTermFinancialInvestmentsMeasuredAtFairValueThroughIncome",
        description="Investimentos financeiros de longo prazo mensurados a valor justo por meio do resultado.",
    )
    financial_investments_measured_at_fair_value_through_other_comprehensive_income: (
        Optional[float]
    ) = Field(
        None,
        alias="financialInvestmentsMeasuredAtFairValueThroughOtherComprehensiveIncome",
        description="Investimentos financeiros mensurados a valor justo por outros resultados abrangentes.",
    )
    financial_investments_measured_at_amortized_cost: Optional[float] = Field(
        None,
        alias="financialInvestmentsMeasuredAtAmortizedCost",
        description="Investimentos financeiros mensurados ao custo amortizado.",
    )
    intangible_asset: Optional[float] = Field(
        None, alias="intangibleAsset", description="Ativo intangível (valor agregado)."
    )
    deferred_taxes: Optional[float] = Field(
        None, alias="deferredTaxes", description="Tributos diferidos no ativo."
    )
    other_operations: Optional[float] = Field(
        None,
        alias="otherOperations",
        description="Outras contas operacionais no ativo.",
    )
    total_liabilities: Optional[float] = Field(
        None, alias="totalLiabilities", description="Total do passivo."
    )
    financial_liabilities_measured_at_fair_value_through_income: Optional[float] = (
        Field(
            None,
            alias="financialLiabilitiesMeasuredAtFairValueThroughIncome",
            description="Passivos financeiros mensurados a valor justo por meio do resultado.",
        )
    )
    financial_liabilities_at_amortized_cost: Optional[float] = Field(
        None,
        alias="financialLiabilitiesAtAmortizedCost",
        description="Passivos financeiros ao custo amortizado.",
    )
    tax_liabilities: Optional[float] = Field(
        None, alias="taxLiabilities", description="Obrigações fiscais (passivo)."
    )
    other_liabilities: Optional[float] = Field(
        None, alias="otherLiabilities", description="Outros passivos."
    )
    controller_shareholders_equity: Optional[float] = Field(
        None,
        alias="controllerShareholdersEquity",
        description="Patrimônio líquido atribuível aos controladores.",
    )
    non_controlling_shareholders_equity: Optional[float] = Field(
        None,
        alias="nonControllingShareholdersEquity",
        description="Participação dos não controladores no patrimônio líquido.",
    )
    revaluation_reserves: Optional[float] = Field(
        None, alias="revaluationReserves", description="Reservas de reavaliação."
    )
    accumulated_profits_or_losses: Optional[float] = Field(
        None,
        alias="accumulatedProfitsOrLosses",
        description="Lucros ou prejuízos acumulados.",
    )
    equity_valuation_adjustments: Optional[float] = Field(
        None,
        alias="equityValuationAdjustments",
        description="Ajustes de avaliação patrimonial.",
    )
    cumulative_conversion_adjustments: Optional[float] = Field(
        None,
        alias="cumulativeConversionAdjustments",
        description="Ajustes acumulados de conversão.",
    )
    national_suppliers: Optional[float] = Field(
        None, alias="nationalSuppliers", description="Fornecedores nacionais."
    )
    foreign_suppliers: Optional[float] = Field(
        None, alias="foreignSuppliers", description="Fornecedores estrangeiros."
    )
    loans_and_financing_in_national_currency: Optional[float] = Field(
        None,
        alias="loansAndFinancingInNationalCurrency",
        description="Empréstimos e financiamentos em moeda nacional (circulante).",
    )
    loans_and_financing_in_foreign_currency: Optional[float] = Field(
        None,
        alias="loansAndFinancingInForeignCurrency",
        description="Empréstimos e financiamentos em moeda estrangeira (circulante).",
    )
    debentures: Optional[float] = Field(
        None, description="Debêntures (passivo circulante)."
    )
    long_term_loans_and_financing_in_national_currency: Optional[float] = Field(
        None,
        alias="longTermLoansAndFinancingInNationalCurrency",
        description="Empréstimos e financiamentos em moeda nacional (não circulante).",
    )
    long_term_loans_and_financing_in_foreign_currency: Optional[float] = Field(
        None,
        alias="longTermLoansAndFinancingInForeignCurrency",
        description="Empréstimos e financiamentos em moeda estrangeira (não circulante).",
    )
    long_term_debentures: Optional[float] = Field(
        None,
        alias="longTermDebentures",
        description="Debêntures (passivo não circulante).",
    )
    other_non_current_liabilities: Optional[float] = Field(
        None,
        alias="otherNonCurrentLiabilities",
        description="Outros passivos não circulantes.",
    )
    profits_and_revenues_to_be_appropriated: Optional[float] = Field(
        None,
        alias="profitsAndRevenuesToBeAppropriated",
        description="Lucros e receitas a apropriar.",
    )
    debits_from_operations: Optional[float] = Field(
        None, alias="debitsFromOperations", description="Débitos oriundos de operações."
    )
    debits_from_insurance_and_reinsurance: Optional[float] = Field(
        None,
        alias="debitsFromInsuranceAndReinsurance",
        description="Débitos de operações de seguros e resseguros.",
    )
    debits_from_complementary_pension: Optional[float] = Field(
        None,
        alias="debitsFromComplementaryPension",
        description="Débitos de operações de previdência complementar.",
    )
    third_party_deposits: Optional[float] = Field(
        None, alias="thirdPartyDeposits", description="Depósitos de terceiros."
    )
    technical_provisions: Optional[float] = Field(
        None,
        alias="technicalProvisions",
        description="Provisões técnicas (seguradoras/previdência).",
    )
    insurance_and_reinsurance: Optional[float] = Field(
        None,
        alias="insuranceAndReinsurance",
        description="Provisões/obrigações de seguros e resseguros.",
    )
    complementary_pension: Optional[float] = Field(
        None,
        alias="complementaryPension",
        description="Obrigações de previdência complementar.",
    )
    capitalization: Optional[float] = Field(
        None, description="Obrigações de capitalização."
    )
    other_debits: Optional[float] = Field(
        None, alias="otherDebits", description="Outros débitos."
    )
    long_term_liabilities: Optional[float] = Field(
        None,
        alias="longTermLiabilities",
        description="Total do passivo de longo prazo.",
    )
    long_term_accounts_payable: Optional[float] = Field(
        None,
        alias="longTermAccountsPayable",
        description="Fornecedores/contas a pagar de longo prazo.",
    )
    long_term_debits_from_operations: Optional[float] = Field(
        None,
        alias="longTermDebitsFromOperations",
        description="Débitos de operações (longo prazo).",
    )
    long_term_technical_provisions: Optional[float] = Field(
        None,
        alias="longTermTechnicalProvisions",
        description="Provisões técnicas de longo prazo.",
    )
    long_term_insurance_and_reinsurance: Optional[float] = Field(
        None,
        alias="longTermInsuranceAndReinsurance",
        description="Obrigações de seguros e resseguros de longo prazo.",
    )
    long_term_complementary_pension: Optional[float] = Field(
        None,
        alias="longTermComplementaryPension",
        description="Obrigações de previdência complementar de longo prazo.",
    )
    long_term_capitalization: Optional[float] = Field(
        None,
        alias="longTermCapitalization",
        description="Obrigações de capitalização de longo prazo.",
    )
    other_long_term_provisions: Optional[float] = Field(
        None,
        alias="otherLongTermProvisions",
        description="Outras provisões de longo prazo.",
    )
    debits_from_capitalization: Optional[float] = Field(
        None,
        alias="debitsFromCapitalization",
        description="Débitos de operações de capitalização.",
    )
    debits_from_other_operations: Optional[float] = Field(
        None,
        alias="debitsFromOtherOperations",
        description="Débitos de outras operações.",
    )
    other_provisions: Optional[float] = Field(
        None, alias="otherProvisions", description="Outras provisões (diversas)."
    )
    advance_for_future_capital_increase: Optional[float] = Field(
        None,
        alias="advanceForFutureCapitalIncrease",
        description="Adiantamento para futuro aumento de capital (AFAC).",
    )


class BalanceSheetHistory(BaseModel):
    balance_sheet_history: Optional[list[BalanceSheetEntry]] = Field(
        None,
        alias="balanceSheetHistory",
        description="Lista de Balanços Patrimoniais anuais, ordenados geralmente do mais recente para o mais antigo.",
    )


class BalanceSheetHistoryQuarterly(BaseModel):
    balance_sheet_history_quarterly: Optional[list[BalanceSheetEntry]] = Field(
        None,
        alias="balanceSheetHistoryQuarterly",
        description="Lista de Balanços Patrimoniais trimestrais, ordenados geralmente do mais recente para o mais antigo.",
    )


class DefaultKeyStatisticsEntry(BaseModel):
    type: Optional[Literal["yearly", "quarterly", "ttm"]] = Field(
        None,
        description="Periodicidade dos dados: `yearly` (anual), `quarterly` (trimestral), `ttm` (Trailing Twelve Months - últimos 12 meses).",
    )
    symbol: Optional[str] = Field(
        None, description="Ticker do ativo ao qual as estatísticas se referem."
    )
    enterprise_value: Optional[float] = Field(
        None,
        alias="enterpriseValue",
        description="Valor da Firma (Enterprise Value - EV): Market Cap + Dívida Total - Caixa.",
    )
    forward_pe: Optional[float] = Field(
        None,
        alias="forwardPE",
        description="Preço / Lucro Projetado (Forward P/E): Preço da Ação / LPA estimado para o próximo período.",
    )
    profit_margins: Optional[float] = Field(
        None,
        alias="profitMargins",
        description="Margem de Lucro Líquida (Lucro Líquido / Receita Líquida). Geralmente em base TTM ou anual.",
    )
    float_shares: Optional[float] = Field(
        None, alias="floatShares", description="Ações em livre circulação (free float)."
    )
    shares_outstanding: Optional[float] = Field(
        None,
        alias="sharesOutstanding",
        description="Número total de ações ordinárias em circulação.",
    )
    held_percent_insiders: Optional[float] = Field(
        None,
        alias="heldPercentInsiders",
        description="Percentual de ações detidas por insiders (administradores, controladores).",
    )
    held_percent_institutions: Optional[float] = Field(
        None,
        alias="heldPercentInstitutions",
        description="Percentual de ações detidas por instituições (fundos, investidores institucionais).",
    )
    beta: Optional[float] = Field(
        None, description="Beta da ação (sensibilidade em relação ao mercado)."
    )
    implied_shares_outstanding: Optional[float] = Field(
        None,
        alias="impliedSharesOutstanding",
        description="Ações implícitas em circulação (considerando diluição/derivativos).",
    )
    book_value: Optional[float] = Field(
        None,
        alias="bookValue",
        description="Valor Patrimonial por Ação (VPA): Patrimônio Líquido / Ações em Circulação.",
    )
    price_to_book: Optional[float] = Field(
        None,
        alias="priceToBook",
        description="Preço sobre Valor Patrimonial (P/VP): Preço da Ação / VPA.",
    )
    last_fiscal_year_end: Optional[date] = Field(
        None,
        alias="lastFiscalYearEnd",
        description="Data de encerramento do último ano fiscal (YYYY-MM-DD).",
    )
    next_fiscal_year_end: Optional[date] = Field(
        None,
        alias="nextFiscalYearEnd",
        description="Data de encerramento do próximo ano fiscal (YYYY-MM-DD).",
    )
    most_recent_quarter: Optional[date] = Field(
        None,
        alias="mostRecentQuarter",
        description="Data de término do trimestre mais recente considerado nos cálculos (YYYY-MM-DD).",
    )
    earnings_quarterly_growth: Optional[float] = Field(
        None,
        alias="earningsQuarterlyGrowth",
        description="Crescimento percentual do lucro líquido no último trimestre em relação ao mesmo trimestre do ano anterior (YoY).",
    )
    earnings_annual_growth: Optional[float] = Field(
        None,
        alias="earningsAnnualGrowth",
        description="Crescimento percentual do lucro líquido no último ano fiscal completo em relação ao ano anterior.",
    )
    net_income_to_common: Optional[float] = Field(
        None,
        alias="netIncomeToCommon",
        description="Lucro Líquido atribuível aos acionistas ordinários (controladores).",
    )
    trailing_eps: Optional[float] = Field(
        None,
        alias="trailingEps",
        description="Lucro Por Ação (LPA) dos Últimos 12 Meses (TTM).",
    )
    forward_eps: Optional[float] = Field(
        None,
        alias="forwardEps",
        description="Lucro Por Ação projetado (próximo período).",
    )
    peg_ratio: Optional[float] = Field(
        None,
        alias="pegRatio",
        description="Índice PEG (P/E dividido pelo crescimento esperado dos lucros).",
    )
    last_split_factor: Optional[str] = Field(
        None,
        alias="lastSplitFactor",
        description="Fator do último desdobramento/grupamento (ex.: 2:1, 1:10).",
    )
    last_split_date: Optional[float] = Field(
        None,
        alias="lastSplitDate",
        description="Data do último desdobramento/grupamento (timestamp UNIX em segundos).",
    )
    enterprise_to_revenue: Optional[float] = Field(
        None,
        alias="enterpriseToRevenue",
        description="Múltiplo EV/Receita (Enterprise Value / Receita Líquida TTM).",
    )
    enterprise_to_ebitda: Optional[float] = Field(
        None,
        alias="enterpriseToEbitda",
        description="Múltiplo EV/EBITDA (Enterprise Value / EBITDA TTM).",
    )
    field_52_week_change: Optional[float] = Field(
        None,
        alias="52WeekChange",
        description="Variação percentual do preço da ação nas últimas 52 semanas.",
    )
    sand_p52_week_change: Optional[float] = Field(
        None,
        alias="SandP52WeekChange",
        description="Variação percentual do índice S&P 500 nas últimas 52 semanas (para referência).",
    )
    last_dividend_value: Optional[float] = Field(
        None,
        alias="lastDividendValue",
        description="Valor do último dividendo ou JCP pago por ação.",
    )
    last_dividend_date: Optional[date] = Field(
        None,
        alias="lastDividendDate",
        description="Data de pagamento (ou 'Data Com') do último dividendo/JCP (YYYY-MM-DD).",
    )
    dividend_yield: Optional[float] = Field(
        None,
        alias="dividendYield",
        description="Dividend Yield (provento anualizado sobre o preço atual).",
    )
    ytd_return: Optional[float] = Field(
        None,
        alias="ytdReturn",
        description="Retorno percentual do preço da ação desde o início do ano atual (Year-to-Date).",
    )
    total_assets: Optional[float] = Field(
        None,
        alias="totalAssets",
        description="Valor total dos ativos registrado no último balanço (anual ou trimestral).",
    )
    updated_at: Optional[date] = Field(
        None,
        alias="updatedAt",
        description="Data da última atualização deste registro específico na fonte de dados (YYYY-MM-DD).",
    )


class DefaultKeyStatistics(BaseModel):
    default_key_statistics: Optional[DefaultKeyStatisticsEntry] = Field(
        None,
        alias="defaultKeyStatistics",
        description="Objeto contendo as principais estatísticas.",
    )


class DefaultKeyStatisticsHistory(BaseModel):
    default_key_statistics_history: Optional[list[DefaultKeyStatisticsEntry]] = Field(
        None,
        alias="defaultKeyStatisticsHistory",
        description="Lista das principais estatísticas anuais, ordenadas geralmente do mais recente para o mais antigo.",
    )


class DefaultKeyStatisticsHistoryQuarterly(BaseModel):
    default_key_statistics_history_quarterly: Optional[
        list[DefaultKeyStatisticsEntry]
    ] = Field(
        None,
        alias="defaultKeyStatisticsHistoryQuarterly",
        description="Lista das principais estatísticas trimestrais, ordenadas geralmente do mais recente para o mais antigo.",
    )


class IncomeStatementEntry(BaseModel):
    id: Optional[str] = Field(
        None, description="Identificador único deste registro de DRE (interno)."
    )
    symbol: Optional[str] = Field(
        None, description="Ticker do ativo ao qual a DRE se refere."
    )
    type: Optional[Literal["yearly", "quarterly"]] = Field(
        None,
        description="Indica a periodicidade da DRE: `yearly` (anual) ou `quarterly` (trimestral).",
    )
    end_date: Optional[date] = Field(
        None,
        alias="endDate",
        description="Data de término do período fiscal ao qual a DRE se refere (YYYY-MM-DD).",
    )
    total_revenue: Optional[float] = Field(
        None, alias="totalRevenue", description="Receita Operacional Líquida."
    )
    cost_of_revenue: Optional[float] = Field(
        None,
        alias="costOfRevenue",
        description="Custo dos Produtos Vendidos (CPV) ou Custo dos Serviços Prestados (CSP).",
    )
    gross_profit: Optional[float] = Field(
        None,
        alias="grossProfit",
        description="Lucro Bruto (Receita Líquida - CPV/CSP).",
    )
    research_development: Optional[float] = Field(
        None,
        alias="researchDevelopment",
        description="Despesas com Pesquisa e Desenvolvimento.",
    )
    selling_general_administrative: Optional[float] = Field(
        None,
        alias="sellingGeneralAdministrative",
        description="Despesas com Vendas, Gerais e Administrativas.",
    )
    non_recurring: Optional[float] = Field(
        None,
        alias="nonRecurring",
        description="Itens Não Recorrentes (pode incluir outras despesas/receitas operacionais).",
    )
    other_operating_expenses: Optional[float] = Field(
        None,
        alias="otherOperatingExpenses",
        description="Outras Despesas Operacionais.",
    )
    total_operating_expenses: Optional[float] = Field(
        None,
        alias="totalOperatingExpenses",
        description="Total das Despesas Operacionais (P&D + SG&A + Outras).",
    )
    operating_income: Optional[float] = Field(
        None,
        alias="operatingIncome",
        description="Lucro Operacional (EBIT - Earnings Before Interest and Taxes). Lucro Bruto - Despesas Operacionais.",
    )
    total_other_income_expense_net: Optional[float] = Field(
        None,
        alias="totalOtherIncomeExpenseNet",
        description="Resultado Financeiro Líquido + Outras Receitas/Despesas.",
    )
    ebit: Optional[float] = Field(
        None,
        description="Lucro Antes dos Juros e Impostos (LAJIR ou EBIT). Geralmente igual a `operatingIncome`.",
    )
    interest_expense: Optional[float] = Field(
        None,
        alias="interestExpense",
        description="Despesas Financeiras (Juros pagos). Note que este campo é negativo.",
    )
    income_before_tax: Optional[float] = Field(
        None,
        alias="incomeBeforeTax",
        description="Lucro Antes do Imposto de Renda e Contribuição Social (LAIR). EBIT + Resultado Financeiro.",
    )
    income_tax_expense: Optional[float] = Field(
        None,
        alias="incomeTaxExpense",
        description="Imposto de Renda e Contribuição Social sobre o Lucro.",
    )
    minority_interest: Optional[float] = Field(
        None,
        alias="minorityInterest",
        description="Participação de Acionistas Não Controladores (no Lucro Líquido).",
    )
    net_income_from_continuing_ops: Optional[float] = Field(
        None,
        alias="netIncomeFromContinuingOps",
        description="Lucro Líquido das Operações Continuadas.",
    )
    discontinued_operations: Optional[float] = Field(
        None,
        alias="discontinuedOperations",
        description="Resultado Líquido das Operações Descontinuadas.",
    )
    extraordinary_items: Optional[float] = Field(
        None, alias="extraordinaryItems", description="Itens Extraordinários."
    )
    effect_of_accounting_charges: Optional[float] = Field(
        None,
        alias="effectOfAccountingCharges",
        description="Efeito de Mudanças Contábeis.",
    )
    other_items: Optional[float] = Field(
        None, alias="otherItems", description="Outros Itens."
    )
    net_income: Optional[float] = Field(
        None, alias="netIncome", description="Lucro Líquido Consolidado do Período."
    )
    net_income_applicable_to_common_shares: Optional[float] = Field(
        None,
        alias="netIncomeApplicableToCommonShares",
        description="Lucro Líquido Atribuível aos Acionistas Controladores (Ações Ordinárias).",
    )
    sales_expenses: Optional[float] = Field(
        None,
        alias="salesExpenses",
        description="Despesas com Vendas (detalhamento, pode estar contido em SG&A).",
    )
    losses_due_to_non_recoverability_of_assets: Optional[float] = Field(
        None,
        alias="lossesDueToNonRecoverabilityOfAssets",
        description="Perdas por Não Recuperabilidade de Ativos (Impairment).",
    )
    other_operating_income: Optional[float] = Field(
        None,
        alias="otherOperatingIncome",
        description="Outras Receitas Operacionais (detalhamento).",
    )
    equity_income_result: Optional[float] = Field(
        None,
        alias="equityIncomeResult",
        description="Resultado de Equivalência Patrimonial.",
    )
    financial_result: Optional[float] = Field(
        None, alias="financialResult", description="Resultado Financeiro Líquido."
    )
    financial_income: Optional[float] = Field(
        None, alias="financialIncome", description="Receitas Financeiras."
    )
    financial_expenses: Optional[float] = Field(
        None,
        alias="financialExpenses",
        description="Despesas Financeiras (valor positivo aqui, diferente de `interestExpense`).",
    )
    current_taxes: Optional[float] = Field(
        None,
        alias="currentTaxes",
        description="Imposto de Renda e Contribuição Social Correntes.",
    )
    deferred_taxes: Optional[float] = Field(
        None,
        alias="deferredTaxes",
        description="Imposto de Renda e Contribuição Social Diferidos.",
    )
    income_before_statutory_participations_and_contributions: Optional[float] = Field(
        None,
        alias="incomeBeforeStatutoryParticipationsAndContributions",
        description="Resultado Antes das Participações Estatutárias.",
    )
    basic_earnings_per_common_share: Optional[float] = Field(
        None,
        alias="basicEarningsPerCommonShare",
        description="Lucro Básico por Ação Ordinária (ON).",
    )
    diluted_earnings_per_common_share: Optional[float] = Field(
        None,
        alias="dilutedEarningsPerCommonShare",
        description="Lucro Diluído por Ação Ordinária (ON).",
    )
    basic_earnings_per_preferred_share: Optional[float] = Field(
        None,
        alias="basicEarningsPerPreferredShare",
        description="Lucro Básico por Ação Preferencial (PN).",
    )
    profit_sharing_and_statutory_contributions: Optional[float] = Field(
        None,
        alias="profitSharingAndStatutoryContributions",
        description="Participações nos Lucros e Contribuições Estatutárias.",
    )
    diluted_earnings_per_preferred_share: Optional[float] = Field(
        None,
        alias="dilutedEarningsPerPreferredShare",
        description="Lucro Diluído por Ação Preferencial (PN).",
    )
    claims_and_operations_costs: Optional[float] = Field(
        None,
        alias="claimsAndOperationsCosts",
        description="Custos com Sinistros e Operações (específico para Seguradoras).",
    )
    administrative_costs: Optional[float] = Field(
        None,
        alias="administrativeCosts",
        description="Despesas Administrativas (detalhamento, pode estar contido em SG&A).",
    )
    other_operating_income_and_expenses: Optional[float] = Field(
        None,
        alias="otherOperatingIncomeAndExpenses",
        description="Outras Receitas e Despesas Operacionais (agregado).",
    )
    earnings_per_share: Optional[float] = Field(
        None,
        alias="earningsPerShare",
        description="Lucro por Ação (LPA) - Geral (pode ser básico ou diluído, verificar contexto).",
    )
    basic_earnings_per_share: Optional[float] = Field(
        None,
        alias="basicEarningsPerShare",
        description="Lucro Básico por Ação (LPA Básico) - Geral.",
    )
    diluted_earnings_per_share: Optional[float] = Field(
        None,
        alias="dilutedEarningsPerShare",
        description="Lucro Diluído por Ação (LPA Diluído) - Geral.",
    )
    insurance_operations: Optional[float] = Field(
        None,
        alias="insuranceOperations",
        description="Resultado de Operações de Seguros (específico para Seguradoras).",
    )
    reinsurance_operations: Optional[float] = Field(
        None,
        alias="reinsuranceOperations",
        description="Resultado de Operações de Resseguros (específico para Seguradoras).",
    )
    complementary_pension_operations: Optional[float] = Field(
        None,
        alias="complementaryPensionOperations",
        description="Resultado de Operações de Previdência Complementar (específico para Seguradoras/Previdência).",
    )
    capitalization_operations: Optional[float] = Field(
        None,
        alias="capitalizationOperations",
        description="Resultado de Operações de Capitalização (específico para Seguradoras).",
    )
    updated_at: Optional[date] = Field(
        None,
        alias="updatedAt",
        description="Data da última atualização deste registro específico na fonte de dados (YYYY-MM-DD).",
    )


class IncomeStatementHistory(BaseModel):
    income_statement_history: Optional[list[IncomeStatementEntry]] = Field(
        None,
        alias="incomeStatementHistory",
        description="Lista de DREs anuais, ordenadas geralmente do mais recente para o mais antigo.",
    )


class IncomeStatementHistoryQuarterly(BaseModel):
    income_statement_history_quarterly: Optional[list[IncomeStatementEntry]] = Field(
        None,
        alias="incomeStatementHistoryQuarterly",
        description="Lista de DREs trimestrais, ordenadas geralmente do mais recente para o mais antigo.",
    )


class FinancialDataEntry(BaseModel):
    symbol: Optional[str] = Field(
        None, description="Ticker do ativo ao qual os dados se referem."
    )
    current_price: Optional[float] = Field(
        None,
        alias="currentPrice",
        description="Preço atual da ação (pode ser ligeiramente defasado).",
    )
    target_high_price: Optional[float] = Field(
        None,
        alias="targetHighPrice",
        description="Preço-alvo mais alto estimado por analistas.",
    )
    target_low_price: Optional[float] = Field(
        None,
        alias="targetLowPrice",
        description="Preço-alvo mais baixo estimado por analistas.",
    )
    target_mean_price: Optional[float] = Field(
        None,
        alias="targetMeanPrice",
        description="Preço-alvo médio estimado por analistas.",
    )
    target_median_price: Optional[float] = Field(
        None,
        alias="targetMedianPrice",
        description="Preço-alvo mediano estimado por analistas.",
    )
    recommendation_mean: Optional[float] = Field(
        None,
        alias="recommendationMean",
        description="Média de recomendações dos analistas (1=Compra Forte, 5=Venda Forte).",
    )
    recommendation_key: Optional[str] = Field(
        None,
        alias="recommendationKey",
        description="Resumo da recomendação (ex.: strong_buy, buy, hold, sell, strong_sell).",
    )
    number_of_analyst_opinions: Optional[float] = Field(
        None,
        alias="numberOfAnalystOpinions",
        description="Número de opiniões de analistas consideradas.",
    )
    ebitda: Optional[float] = Field(
        None,
        description="Lucro Antes de Juros, Impostos, Depreciação e Amortização (LAJIDA ou EBITDA). Geralmente TTM.",
    )
    quick_ratio: Optional[float] = Field(
        None,
        alias="quickRatio",
        description="Índice de Liquidez Seca ((Ativo Circulante - Estoques) / Passivo Circulante).",
    )
    current_ratio: Optional[float] = Field(
        None,
        alias="currentRatio",
        description="Índice de Liquidez Corrente (Ativo Circulante / Passivo Circulante).",
    )
    debt_to_equity: Optional[float] = Field(
        None,
        alias="debtToEquity",
        description="Índice Dívida Líquida / Patrimônio Líquido.",
    )
    revenue_per_share: Optional[float] = Field(
        None,
        alias="revenuePerShare",
        description="Receita Líquida por Ação (Receita Líquida TTM / Ações em Circulação).",
    )
    return_on_assets: Optional[float] = Field(
        None,
        alias="returnOnAssets",
        description="Retorno sobre Ativos (ROA): Lucro Líquido TTM / Ativo Total Médio.",
    )
    return_on_equity: Optional[float] = Field(
        None,
        alias="returnOnEquity",
        description="Retorno sobre Patrimônio Líquido (ROE): Lucro Líquido TTM / Patrimônio Líquido Médio.",
    )
    earnings_growth: Optional[float] = Field(
        None,
        alias="earningsGrowth",
        description="Crescimento do Lucro Líquido (geralmente trimestral YoY, como `earningsQuarterlyGrowth`).",
    )
    revenue_growth: Optional[float] = Field(
        None,
        alias="revenueGrowth",
        description="Crescimento da Receita Líquida (geralmente trimestral YoY).",
    )
    gross_margins: Optional[float] = Field(
        None,
        alias="grossMargins",
        description="Margem Bruta (Lucro Bruto TTM / Receita Líquida TTM).",
    )
    ebitda_margins: Optional[float] = Field(
        None,
        alias="ebitdaMargins",
        description="Margem EBITDA (EBITDA TTM / Receita Líquida TTM).",
    )
    operating_margins: Optional[float] = Field(
        None,
        alias="operatingMargins",
        description="Margem Operacional (EBIT TTM / Receita Líquida TTM).",
    )
    profit_margins: Optional[float] = Field(
        None,
        alias="profitMargins",
        description="Margem Líquida (Lucro Líquido TTM / Receita Líquida TTM). Sinônimo do campo de mesmo nome em `DefaultKeyStatisticsEntry`.",
    )
    total_cash: Optional[float] = Field(
        None,
        alias="totalCash",
        description="Caixa e Equivalentes de Caixa + Aplicações Financeiras de Curto Prazo (último balanço).",
    )
    total_cash_per_share: Optional[float] = Field(
        None,
        alias="totalCashPerShare",
        description="Caixa Total por Ação (Caixa Total / Ações em Circulação).",
    )
    total_debt: Optional[float] = Field(
        None,
        alias="totalDebt",
        description="Dívida Bruta Total (Dívida de Curto Prazo + Dívida de Longo Prazo - último balanço).",
    )
    total_revenue: Optional[float] = Field(
        None,
        alias="totalRevenue",
        description="Receita Líquida Total (geralmente TTM).",
    )
    gross_profits: Optional[float] = Field(
        None, alias="grossProfits", description="Lucro Bruto (geralmente TTM)."
    )
    operating_cashflow: Optional[float] = Field(
        None,
        alias="operatingCashflow",
        description="Fluxo de Caixa das Operações (FCO) - (geralmente TTM).",
    )
    free_cashflow: Optional[float] = Field(
        None,
        alias="freeCashflow",
        description="Fluxo de Caixa Livre (FCO - CAPEX) - (geralmente TTM).",
    )
    financial_currency: Optional[str] = Field(
        None,
        alias="financialCurrency",
        description="Moeda na qual os dados financeiros são reportados (ex: `BRL`, `USD`).",
    )
    updated_at: Optional[date] = Field(
        None,
        alias="updatedAt",
        description="Data da última atualização deste registro específico na fonte de dados (YYYY-MM-DD).",
    )
    type: Optional[Literal["yearly", "quarterly", "ttm"]] = Field(
        None,
        description="Periodicidade dos dados: `yearly` (anual), `quarterly` (trimestral), `ttm` (Trailing Twelve Months).",
    )


class FinancialData(BaseModel):
    financial_data: Optional[FinancialDataEntry] = Field(
        None,
        alias="financialData",
        description="Objeto contendo os dados financeiros TTM.",
    )


class FinancialDataHistory(BaseModel):
    financial_data_history: Optional[list[FinancialDataEntry]] = Field(
        None,
        alias="financialDataHistory",
        description="Lista de dados financeiros anuais, ordenados geralmente do mais recente para o mais antigo.",
    )


class FinancialDataHistoryQuarterly(BaseModel):
    financial_data_history_quarterly: Optional[list[FinancialDataEntry]] = Field(
        None,
        alias="financialDataHistoryQuarterly",
        description="Lista de dados financeiros trimestrais, ordenados geralmente do mais recente para o mais antigo.",
    )


class ValueAddedEntry(BaseModel):
    symbol: Optional[str] = Field(
        None, description="Ticker do ativo ao qual a DVA se refere."
    )
    type: Optional[Literal["yearly", "quarterly"]] = Field(
        None,
        description="Indica a periodicidade da DVA: `yearly` (anual) ou `quarterly` (trimestral).",
    )
    end_date: Optional[date] = Field(
        None,
        alias="endDate",
        description="Data de término do período fiscal ao qual a DVA se refere (YYYY-MM-DD).",
    )
    revenue: Optional[float] = Field(
        None,
        description="Receitas (Venda de Mercadorias, Produtos e Serviços, etc.). Item 1 da DVA.",
    )
    financial_intermediation_revenue: Optional[float] = Field(
        None,
        alias="financialIntermediationRevenue",
        description="Receita de Intermediação Financeira (específico para bancos).",
    )
    revenue_from_the_provision_of_services: Optional[float] = Field(
        None,
        alias="revenueFromTheProvisionOfServices",
        description="Receita da Prestação de Serviços (detalhamento).",
    )
    provision_or_reversal_of_expected_credit_risk_losses: Optional[float] = Field(
        None,
        alias="provisionOrReversalOfExpectedCreditRiskLosses",
        description="Provisão/Reversão de Perdas com Risco de Crédito (PCLD).",
    )
    other_revenues: Optional[float] = Field(
        None, alias="otherRevenues", description="Outras Receitas."
    )
    financial_intermediation_expenses: Optional[float] = Field(
        None,
        alias="financialIntermediationExpenses",
        description="Despesas de Intermediação Financeira (específico para bancos).",
    )
    supplies_purchased_from_third_parties: Optional[float] = Field(
        None,
        alias="suppliesPurchasedFromThirdParties",
        description="Insumos Adquiridos de Terceiros (Custo de Mercadorias, Matérias-Primas). Item 2 da DVA.",
    )
    materials_energy_and_others: Optional[float] = Field(
        None,
        alias="materialsEnergyAndOthers",
        description="Custos com Materiais, Energia, Serviços de Terceiros e Outros.",
    )
    services: Optional[float] = Field(
        None, description="Serviços de Terceiros (detalhamento)."
    )
    loss_or_recovery_of_asset_values: Optional[float] = Field(
        None,
        alias="lossOrRecoveryOfAssetValues",
        description="Perda / Recuperação de Valores de Ativos (Impairment).",
    )
    other_supplies: Optional[float] = Field(
        None, alias="otherSupplies", description="Outros Insumos."
    )
    gross_added_value: Optional[float] = Field(
        None,
        alias="grossAddedValue",
        description="Valor Adicionado Bruto (Receitas - Insumos). Item 3 da DVA.",
    )
    retentions: Optional[float] = Field(
        None,
        description="Retenções (Depreciação, Amortização e Exaustão). Item 4 da DVA.",
    )
    depreciation_and_amortization: Optional[float] = Field(
        None,
        alias="depreciationAndAmortization",
        description="Depreciação e Amortização.",
    )
    other_retentions: Optional[float] = Field(
        None, alias="otherRetentions", description="Outras Retenções (Exaustão, etc.)."
    )
    net_added_value: Optional[float] = Field(
        None,
        alias="netAddedValue",
        description="Valor Adicionado Líquido Produzido pela Entidade (Bruto - Retenções). Item 5 da DVA.",
    )
    added_value_received_by_transfer: Optional[float] = Field(
        None,
        alias="addedValueReceivedByTransfer",
        description="Valor Adicionado Recebido em Transferência (Resultado de Equivalência Patrimonial, Receitas Financeiras, etc.). Item 6 da DVA.",
    )
    equity_income_result: Optional[float] = Field(
        None,
        alias="equityIncomeResult",
        description="Resultado de Equivalência Patrimonial (como receita na DVA).",
    )
    other_values_received_by_transfer: Optional[float] = Field(
        None,
        alias="otherValuesReceivedByTransfer",
        description="Outros Valores Recebidos (Receitas Financeiras, Aluguéis, etc.).",
    )
    added_value_to_distribute: Optional[float] = Field(
        None,
        alias="addedValueToDistribute",
        description="Valor Adicionado Total a Distribuir (Líquido Produzido + Recebido em Transferência). Item 7 da DVA.",
    )
    distribution_of_added_value: Optional[float] = Field(
        None,
        alias="distributionOfAddedValue",
        description="Distribuição do Valor Adicionado (Soma dos itens seguintes). Item 8 da DVA.",
    )
    team_remuneration: Optional[float] = Field(
        None,
        alias="teamRemuneration",
        description="Pessoal e Encargos (Salários, Benefícios, FGTS).",
    )
    taxes: Optional[float] = Field(
        None,
        description="Impostos, Taxas e Contribuições (Federais, Estaduais, Municipais).",
    )
    federal_taxes: Optional[float] = Field(
        None,
        alias="federalTaxes",
        description="Impostos Federais (IRPJ, CSLL, PIS, COFINS, IPI).",
    )
    state_taxes: Optional[float] = Field(
        None, alias="stateTaxes", description="Impostos Estaduais (ICMS)."
    )
    municipal_taxes: Optional[float] = Field(
        None, alias="municipalTaxes", description="Impostos Municipais (ISS)."
    )
    remuneration_of_third_party_capitals: Optional[float] = Field(
        None,
        alias="remunerationOfThirdPartyCapitals",
        description="Remuneração de Capitais de Terceiros (Juros, Aluguéis).",
    )
    equity_remuneration: Optional[float] = Field(
        None,
        alias="equityRemuneration",
        description="Remuneração de Capitais Próprios (JCP, Dividendos, Lucros Retidos).",
    )
    interest_on_own_equity: Optional[float] = Field(
        None,
        alias="interestOnOwnEquity",
        description="Juros sobre o Capital Próprio (JCP).",
    )
    dividends: Optional[float] = Field(None, description="Dividendos Distribuídos.")
    retained_earnings_or_loss: Optional[float] = Field(
        None,
        alias="retainedEarningsOrLoss",
        description="Lucros Retidos ou Prejuízo do Exercício.",
    )
    non_controlling_share_of_retained_earnings: Optional[float] = Field(
        None,
        alias="nonControllingShareOfRetainedEarnings",
        description="Participação dos Não Controladores nos Lucros Retidos.",
    )
    other_distributions: Optional[float] = Field(
        None, alias="otherDistributions", description="Outras Distribuições."
    )
    product_sales: Optional[float] = Field(
        None,
        alias="productSales",
        description="Venda de Produtos e Serviços (detalhamento).",
    )
    construction_of_own_assets: Optional[float] = Field(
        None,
        alias="constructionOfOwnAssets",
        description="Construção de Ativos Próprios.",
    )
    provision_or_reversal_of_doubtful_accounts: Optional[float] = Field(
        None,
        alias="provisionOrReversalOfDoubtfulAccounts",
        description="Provisão/Reversão para Créditos de Liquidação Duvidosa (PCLD - como receita/despesa na DVA).",
    )
    costs_with_products_sold: Optional[float] = Field(
        None,
        alias="costsWithProductsSold",
        description="Custos dos Produtos, Mercadorias e Serviços Vendidos (detalhamento).",
    )
    third_party_materials_and_services: Optional[float] = Field(
        None,
        alias="thirdPartyMaterialsAndServices",
        description="Materiais, Energia, Serviços de Terceiros.",
    )
    loss_or_recovery_of_assets: Optional[float] = Field(
        None,
        alias="lossOrRecoveryOfAssets",
        description="Perda/Recuperação de Valores de Ativos (Impairment - como custo/receita).",
    )
    net_added_value_produced: Optional[float] = Field(
        None,
        alias="netAddedValueProduced",
        description="Valor Adicionado Líquido Produzido (sinônimo de `netAddedValue`).",
    )
    added_value_received_on_transfer: Optional[float] = Field(
        None,
        alias="addedValueReceivedOnTransfer",
        description="Valor Adicionado Recebido em Transferência (sinônimo de `addedValueReceivedByTransfer`).",
    )
    financial_income: Optional[float] = Field(
        None,
        alias="financialIncome",
        description="Receitas Financeiras (como valor recebido em transferência).",
    )
    insurance_operations_revenue: Optional[float] = Field(
        None,
        alias="insuranceOperationsRevenue",
        description="Receita com Operações de Seguros (específico para Seguradoras).",
    )
    complementary_pension_operations_revenue: Optional[float] = Field(
        None,
        alias="complementaryPensionOperationsRevenue",
        description="Receita com Operações de Previdência Complementar.",
    )
    fees_revenue: Optional[float] = Field(
        None, alias="feesRevenue", description="Receita com Taxas e Comissões."
    )
    variations_of_technical_provisions: Optional[float] = Field(
        None,
        alias="variationsOfTechnicalProvisions",
        description="Variações das Provisões Técnicas (específico para Seguradoras).",
    )
    insurance_operations_variations: Optional[float] = Field(
        None,
        alias="insuranceOperationsVariations",
        description="Variações de Operações de Seguros.",
    )
    pension_operations_variations: Optional[float] = Field(
        None,
        alias="pensionOperationsVariations",
        description="Variações de Operações de Previdência.",
    )
    other_variations: Optional[float] = Field(
        None, alias="otherVariations", description="Outras Variações."
    )
    net_operating_revenue: Optional[float] = Field(
        None,
        alias="netOperatingRevenue",
        description="Receita Operacional Líquida (detalhamento).",
    )
    claims_and_benefits: Optional[float] = Field(
        None, alias="claimsAndBenefits", description="Sinistros Retidos e Benefícios."
    )
    variation_in_deferred_selling_expenses: Optional[float] = Field(
        None,
        alias="variationInDeferredSellingExpenses",
        description="Variação nas Despesas de Comercialização Diferidas.",
    )
    results_of_ceded_reinsurance_operations: Optional[float] = Field(
        None,
        alias="resultsOfCededReinsuranceOperations",
        description="Resultados de Operações de Resseguros Cedidos.",
    )
    result_of_coinsurance_operations_assigned: Optional[float] = Field(
        None,
        alias="resultOfCoinsuranceOperationsAssigned",
        description="Resultado de Operações de Cosseguros Cedidos.",
    )
    total_added_value_to_distribute: Optional[float] = Field(
        None,
        alias="totalAddedValueToDistribute",
        description="Valor Adicionado Total a Distribuir (sinônimo de `addedValueToDistribute`).",
    )
    own_equity_remuneration: Optional[float] = Field(
        None,
        alias="ownEquityRemuneration",
        description="Remuneração de Capitais Próprios (sinônimo de `equityRemuneration`).",
    )
    updated_at: Optional[date] = Field(
        None,
        alias="updatedAt",
        description="Data da última atualização deste registro específico na fonte de dados (YYYY-MM-DD).",
    )


class ValueAddedHistory(BaseModel):
    value_added_history: Optional[list[ValueAddedEntry]] = Field(
        None,
        alias="valueAddedHistory",
        description="Lista de DVAs anuais, ordenadas geralmente do mais recente para o mais antigo.",
    )


class ValueAddedHistoryQuarterly(BaseModel):
    value_added_history_quarterly: Optional[list[ValueAddedEntry]] = Field(
        None,
        alias="valueAddedHistoryQuarterly",
        description="Lista de DVAs trimestrais, ordenadas geralmente do mais recente para o mais antigo.",
    )


class CashflowEntry(BaseModel):
    symbol: Optional[str] = Field(
        None, description="Ticker do ativo ao qual a DFC se refere."
    )
    type: Optional[Literal["yearly", "quarterly"]] = Field(
        None,
        description="Indica a periodicidade da DFC: `yearly` (anual) ou `quarterly` (trimestral).",
    )
    end_date: Optional[date] = Field(
        None,
        alias="endDate",
        description="Data de término do período fiscal ao qual a DFC se refere (YYYY-MM-DD).",
    )
    operating_cash_flow: Optional[float] = Field(
        None,
        alias="operatingCashFlow",
        description="Fluxo de Caixa das Atividades Operacionais (FCO).",
    )
    income_from_operations: Optional[float] = Field(
        None,
        alias="incomeFromOperations",
        description="Caixa Gerado nas Operações (antes das variações de ativos/passivos).",
    )
    net_income_before_taxes: Optional[float] = Field(
        None,
        alias="netIncomeBeforeTaxes",
        description="Lucro líquido antes dos impostos (base para reconciliação pelo método indireto).",
    )
    adjustments_to_profit_or_loss: Optional[float] = Field(
        None,
        alias="adjustmentsToProfitOrLoss",
        description="Ajustes ao lucro/prejuízo (depreciação, amortização, equivalência patrimonial, variações não caixa).",
    )
    changes_in_assets_and_liabilities: Optional[float] = Field(
        None,
        alias="changesInAssetsAndLiabilities",
        description="Variações em Ativos e Passivos Operacionais (Clientes, Estoques, Fornecedores, etc.).",
    )
    other_operating_activities: Optional[float] = Field(
        None,
        alias="otherOperatingActivities",
        description="Outras Atividades Operacionais (Juros pagos/recebidos, Impostos pagos, etc.).",
    )
    investment_cash_flow: Optional[float] = Field(
        None,
        alias="investmentCashFlow",
        description="Fluxo de Caixa das Atividades de Investimento (FCI) (Compra/Venda de Imobilizado, Investimentos).",
    )
    financing_cash_flow: Optional[float] = Field(
        None,
        alias="financingCashFlow",
        description="Fluxo de Caixa das Atividades de Financiamento (FCF) (Captação/Pagamento de Empréstimos, Emissão/Recompra de Ações, Dividendos pagos).",
    )
    exchange_variation_without_cash: Optional[float] = Field(
        None,
        alias="exchangeVariationWithoutCash",
        description="Variação cambial sem efeito caixa (ajuste de conversão).",
    )
    foreign_exchange_rate_without_cash: Optional[float] = Field(
        None,
        alias="foreignExchangeRateWithoutCash",
        description="Efeito da Variação Cambial sobre o Caixa e Equivalentes.",
    )
    increase_or_decrease_in_cash: Optional[float] = Field(
        None,
        alias="increaseOrDecreaseInCash",
        description="Aumento ou Redução Líquida de Caixa e Equivalentes (FCO + FCI + FCF + Variação Cambial).",
    )
    initial_cash_balance: Optional[float] = Field(
        None,
        alias="initialCashBalance",
        description="Saldo Inicial de Caixa e Equivalentes no início do período.",
    )
    final_cash_balance: Optional[float] = Field(
        None,
        alias="finalCashBalance",
        description="Saldo Final de Caixa e Equivalentes no final do período.",
    )
    cash_generated_in_operations: Optional[float] = Field(
        None,
        alias="cashGeneratedInOperations",
        description="Caixa gerado nas operações (após variações no capital de giro).",
    )
    updated_at: Optional[date] = Field(
        None,
        alias="updatedAt",
        description="Data da última atualização deste registro específico na fonte de dados (YYYY-MM-DD).",
    )


class CashflowHistory(BaseModel):
    cashflow_history: Optional[list[CashflowEntry]] = Field(
        None,
        alias="cashflowHistory",
        description="Lista de DFCs anuais, ordenadas geralmente do mais recente para o mais antigo.",
    )


class CashflowHistoryQuarterly(BaseModel):
    cashflow_history_quarterly: Optional[list[CashflowEntry]] = Field(
        None,
        alias="cashflowHistoryQuarterly",
        description="Lista de DFCs trimestrais, ordenadas geralmente do mais recente para o mais antigo.",
    )


class QuoteResult(BaseModel):
    symbol: Optional[str] = Field(
        None, description="Ticker (símbolo) do ativo (ex: `PETR4`, `^BVSP`)."
    )
    currency: Optional[str] = Field(
        None,
        description="Moeda na qual os valores monetários são expressos (geralmente `BRL`).",
    )
    two_hundred_day_average: Optional[float] = Field(
        None,
        alias="twoHundredDayAverage",
        description="Média móvel simples dos preços de fechamento dos últimos 200 dias.",
    )
    two_hundred_day_average_change: Optional[float] = Field(
        None,
        alias="twoHundredDayAverageChange",
        description="Variação absoluta entre o preço atual e a média de 200 dias.",
    )
    two_hundred_day_average_change_percent: Optional[float] = Field(
        None,
        alias="twoHundredDayAverageChangePercent",
        description="Variação percentual entre o preço atual e a média de 200 dias.",
    )
    market_cap: Optional[float] = Field(
        None,
        alias="marketCap",
        description="Capitalização de mercado total do ativo (Preço Atual x Ações em Circulação).",
    )
    short_name: Optional[str] = Field(
        None,
        alias="shortName",
        description="Nome curto ou abreviado da empresa ou ativo.",
    )
    long_name: Optional[str] = Field(
        None,
        alias="longName",
        description="Nome longo ou completo da empresa ou ativo.",
    )
    regular_market_change: Optional[float] = Field(
        None,
        alias="regularMarketChange",
        description="Variação absoluta do preço no dia atual em relação ao fechamento anterior.",
    )
    regular_market_change_percent: Optional[float] = Field(
        None,
        alias="regularMarketChangePercent",
        description="Variação percentual do preço no dia atual em relação ao fechamento anterior.",
    )
    regular_market_time: Optional[datetime] = Field(
        None,
        alias="regularMarketTime",
        description="Data e hora da última atualização da cotação (último negócio registrado). Formato ISO 8601.",
    )
    regular_market_price: Optional[float] = Field(
        None,
        alias="regularMarketPrice",
        description="Preço atual ou do último negócio registrado.",
    )
    regular_market_day_high: Optional[float] = Field(
        None,
        alias="regularMarketDayHigh",
        description="Preço máximo atingido no dia de negociação atual.",
    )
    regular_market_day_range: Optional[str] = Field(
        None,
        alias="regularMarketDayRange",
        description="String formatada mostrando o intervalo de preço do dia (Mínimo - Máximo).",
    )
    regular_market_day_low: Optional[float] = Field(
        None,
        alias="regularMarketDayLow",
        description="Preço mínimo atingido no dia de negociação atual.",
    )
    regular_market_volume: Optional[float] = Field(
        None,
        alias="regularMarketVolume",
        description="Volume financeiro negociado no dia atual.",
    )
    regular_market_previous_close: Optional[float] = Field(
        None,
        alias="regularMarketPreviousClose",
        description="Preço de fechamento do pregão anterior.",
    )
    regular_market_open: Optional[float] = Field(
        None,
        alias="regularMarketOpen",
        description="Preço de abertura no dia de negociação atual.",
    )
    average_daily_volume3_month: Optional[float] = Field(
        None,
        alias="averageDailyVolume3Month",
        description="Média do volume financeiro diário negociado nos últimos 3 meses.",
    )
    average_daily_volume10_day: Optional[float] = Field(
        None,
        alias="averageDailyVolume10Day",
        description="Média do volume financeiro diário negociado nos últimos 10 dias.",
    )
    fifty_two_week_low_change: Optional[float] = Field(
        None,
        alias="fiftyTwoWeekLowChange",
        description="Variação absoluta entre o preço atual e o preço mínimo das últimas 52 semanas.",
    )
    fifty_two_week_range: Optional[str] = Field(
        None,
        alias="fiftyTwoWeekRange",
        description="String formatada mostrando o intervalo de preço das últimas 52 semanas (Mínimo - Máximo).",
    )
    fifty_two_week_high_change: Optional[float] = Field(
        None,
        alias="fiftyTwoWeekHighChange",
        description="Variação absoluta entre o preço atual e o preço máximo das últimas 52 semanas.",
    )
    fifty_two_week_high_change_percent: Optional[float] = Field(
        None,
        alias="fiftyTwoWeekHighChangePercent",
        description="Variação percentual entre o preço atual e o preço máximo das últimas 52 semanas.",
    )
    fifty_two_week_low: Optional[float] = Field(
        None,
        alias="fiftyTwoWeekLow",
        description="Preço mínimo atingido nas últimas 52 semanas.",
    )
    fifty_two_week_high: Optional[float] = Field(
        None,
        alias="fiftyTwoWeekHigh",
        description="Preço máximo atingido nas últimas 52 semanas.",
    )
    price_earnings: Optional[float] = Field(
        None,
        alias="priceEarnings",
        description="Indicador Preço/Lucro (P/L): Preço Atual / Lucro Por Ação (LPA) TTM. Retornado se `fundamental=true`.",
    )
    earnings_per_share: Optional[float] = Field(
        None,
        alias="earningsPerShare",
        description="Lucro Por Ação (LPA) dos últimos 12 meses (TTM). Retornado se `fundamental=true`.",
    )
    logourl: Optional[str] = Field(
        None, description="URL da imagem do logo do ativo/empresa."
    )
    updated_at: Optional[datetime] = Field(
        None,
        alias="updatedAt",
        description="Timestamp da última atualização dos dados do índice na fonte (aplicável principalmente a índices, como `^BVSP`). Formato ISO 8601.",
    )
    used_interval: Optional[str] = Field(
        None,
        alias="usedInterval",
        description="O intervalo (`interval`) efetivamente utilizado pela API para retornar os dados históricos, caso solicitado.",
    )
    used_range: Optional[str] = Field(
        None,
        alias="usedRange",
        description="O período (`range`) efetivamente utilizado pela API para retornar os dados históricos, caso solicitado.",
    )
    historical_data_price: Optional[list[HistoricalDataPrice]] = Field(
        None,
        alias="historicalDataPrice",
        description="Array contendo a série histórica de preços, retornado apenas se os parâmetros `range` e/ou `interval` forem especificados na requisição.",
    )
    valid_ranges: Optional[list[str]] = Field(
        None,
        alias="validRanges",
        description="Lista dos valores válidos que podem ser utilizados no parâmetro `range` para este ativo específico.",
    )
    valid_intervals: Optional[list[str]] = Field(
        None,
        alias="validIntervals",
        description="Lista dos valores válidos que podem ser utilizados no parâmetro `interval` para este ativo específico.",
    )
    dividends_data: Optional[DividendsData] = Field(
        None,
        alias="dividendsData",
        description="Objeto contendo informações sobre dividendos, JCP e outros eventos corporativos. Retornado apenas se `dividends=true` for especificado na requisição.",
    )
    summary_profile: Optional[SummaryProfile] = Field(
        None,
        alias="summaryProfile",
        description="Resumo do perfil da empresa. Retornado apenas se `modules` incluir `summaryProfile`.",
    )
    balance_sheet_history: Optional[list[BalanceSheetEntry]] = Field(
        None,
        alias="balanceSheetHistory",
        description="Histórico **anual** do Balanço Patrimonial. Retornado apenas se `modules` incluir `balanceSheetHistory`.",
    )
    balance_sheet_history_quarterly: Optional[list[BalanceSheetEntry]] = Field(
        None,
        alias="balanceSheetHistoryQuarterly",
        description="Histórico **trimestral** do Balanço Patrimonial. Retornado apenas se `modules` incluir `balanceSheetHistoryQuarterly`.",
    )
    default_key_statistics: Optional[DefaultKeyStatisticsEntry] = Field(
        None,
        alias="defaultKeyStatistics",
        description="Principais estatísticas financeiras atuais/TTM. Retornado apenas se `modules` incluir `defaultKeyStatistics`.",
    )
    default_key_statistics_history: Optional[list[DefaultKeyStatisticsEntry]] = Field(
        None,
        alias="defaultKeyStatisticsHistory",
        description="Histórico **anual** das principais estatísticas. Retornado apenas se `modules` incluir `defaultKeyStatisticsHistory`.",
    )
    default_key_statistics_history_quarterly: Optional[
        list[DefaultKeyStatisticsEntry]
    ] = Field(
        None,
        alias="defaultKeyStatisticsHistoryQuarterly",
        description="Histórico **trimestral** das principais estatísticas. Retornado apenas se `modules` incluir `defaultKeyStatisticsHistoryQuarterly`.",
    )
    income_statement_history: Optional[list[IncomeStatementEntry]] = Field(
        None,
        alias="incomeStatementHistory",
        description="Histórico **anual** da Demonstração do Resultado (DRE). Retornado apenas se `modules` incluir `incomeStatementHistory`.",
    )
    income_statement_history_quarterly: Optional[list[IncomeStatementEntry]] = Field(
        None,
        alias="incomeStatementHistoryQuarterly",
        description="Histórico **trimestral** da Demonstração do Resultado (DRE). Retornado apenas se `modules` incluir `incomeStatementHistoryQuarterly`.",
    )
    financial_data: Optional[FinancialDataEntry] = Field(
        None,
        alias="financialData",
        description="Dados financeiros e indicadores TTM. Retornado apenas se `modules` incluir `financialData`.",
    )
    financial_data_history: Optional[list[FinancialDataEntry]] = Field(
        None,
        alias="financialDataHistory",
        description="Histórico **anual** de dados financeiros e indicadores. Retornado apenas se `modules` incluir `financialDataHistory`.",
    )
    financial_data_history_quarterly: Optional[list[FinancialDataEntry]] = Field(
        None,
        alias="financialDataHistoryQuarterly",
        description="Histórico **trimestral** de dados financeiros e indicadores. Retornado apenas se `modules` incluir `financialDataHistoryQuarterly`.",
    )
    value_added_history: Optional[list[ValueAddedEntry]] = Field(
        None,
        alias="valueAddedHistory",
        description="Histórico **anual** da Demonstração do Valor Adicionado (DVA). Retornado apenas se `modules` incluir `valueAddedHistory`.",
    )
    value_added_history_quarterly: Optional[list[ValueAddedEntry]] = Field(
        None,
        alias="valueAddedHistoryQuarterly",
        description="Histórico **trimestral** da Demonstração do Valor Adicionado (DVA). Retornado apenas se `modules` incluir `valueAddedHistoryQuarterly`.",
    )
    cashflow_history: Optional[list[CashflowEntry]] = Field(
        None,
        alias="cashflowHistory",
        description="Histórico **anual** da Demonstração do Fluxo de Caixa (DFC). Retornado apenas se `modules` incluir `cashflowHistory`.",
    )
    cashflow_history_quarterly: Optional[list[CashflowEntry]] = Field(
        None,
        alias="cashflowHistoryQuarterly",
        description="Histórico **trimestral** da Demonstração do Fluxo de Caixa (DFC). Retornado apenas se `modules` incluir `cashflowHistoryQuarterly`.",
    )


class QuoteResponse(BaseModel):
    results: Optional[list[QuoteResult]] = Field(
        None,
        description="Array contendo os resultados detalhados para cada ticker solicitado.",
    )
    requested_at: Optional[datetime] = Field(
        None,
        alias="requestedAt",
        description="Timestamp indicando quando a requisição foi recebida pelo servidor. Formato ISO 8601.",
    )
    took: Optional[str] = Field(
        None,
        description="Tempo aproximado que o servidor levou para processar a requisição, em formato de string (ex: `746ms`).",
        example="746ms",
    )


class CryptoHistoricalData(BaseModel):
    date: Optional[int] = Field(
        None, description="Data do ponto de dados, representada como um timestamp UNIX."
    )
    open: Optional[float] = Field(
        None, description="Preço de abertura da criptomoeda no intervalo."
    )
    high: Optional[float] = Field(
        None, description="Preço máximo atingido no intervalo."
    )
    low: Optional[float] = Field(
        None, description="Preço mínimo atingido no intervalo."
    )
    close: Optional[float] = Field(
        None, description="Preço de fechamento da criptomoeda no intervalo."
    )
    volume: Optional[int] = Field(
        None,
        description="Volume negociado no intervalo (na criptomoeda ou na moeda de referência, verificar contexto).",
    )
    adjusted_close: Optional[float] = Field(
        None,
        alias="adjustedClose",
        description="Preço de fechamento ajustado (geralmente igual ao `close` para cripto).",
    )


class CryptoCoin(BaseModel):
    currency: Optional[str] = Field(
        None,
        description="Sigla da moeda fiduciária na qual os preços estão cotados (ex: `BRL`, `USD`).",
    )
    currency_rate_from_usd: Optional[float] = Field(
        None,
        alias="currencyRateFromUSD",
        description="Taxa de câmbio da `currency` em relação ao USD (Dólar Americano). `1 USD = X currency`.",
    )
    coin_name: Optional[str] = Field(
        None,
        alias="coinName",
        description="Nome completo da criptomoeda (ex: `Bitcoin`, `Ethereum`).",
    )
    coin: Optional[str] = Field(
        None, description="Sigla (ticker) da criptomoeda (ex: `BTC`, `ETH`)."
    )
    regular_market_change: Optional[float] = Field(
        None,
        alias="regularMarketChange",
        description="Variação absoluta do preço nas últimas 24 horas (ou período relevante).",
    )
    regular_market_price: Optional[float] = Field(
        None,
        alias="regularMarketPrice",
        description="Preço atual da criptomoeda na `currency` especificada.",
    )
    regular_market_change_percent: Optional[float] = Field(
        None,
        alias="regularMarketChangePercent",
        description="Variação percentual do preço nas últimas 24 horas (ou período relevante).",
    )
    regular_market_day_low: Optional[float] = Field(
        None,
        alias="regularMarketDayLow",
        description="Preço mínimo nas últimas 24 horas (ou período relevante).",
    )
    regular_market_day_high: Optional[float] = Field(
        None,
        alias="regularMarketDayHigh",
        description="Preço máximo nas últimas 24 horas (ou período relevante).",
    )
    regular_market_day_range: Optional[str] = Field(
        None,
        alias="regularMarketDayRange",
        description="String formatada mostrando o intervalo de preço das últimas 24h (Mínimo - Máximo).",
    )
    regular_market_volume: Optional[int] = Field(
        None,
        alias="regularMarketVolume",
        description="Volume negociado nas últimas 24 horas (na `currency` especificada).",
    )
    market_cap: Optional[int] = Field(
        None,
        alias="marketCap",
        description="Capitalização de mercado da criptomoeda na `currency` especificada.",
    )
    regular_market_time: Optional[datetime] = Field(
        None,
        alias="regularMarketTime",
        description="Timestamp da última atualização da cotação. Formato ISO 8601.",
    )
    coin_image_url: Optional[str] = Field(
        None, alias="coinImageUrl", description="URL da imagem do logo da criptomoeda."
    )
    used_interval: Optional[str] = Field(
        None,
        alias="usedInterval",
        description="O intervalo (`interval`) efetivamente utilizado para os dados históricos, se solicitado.",
    )
    used_range: Optional[str] = Field(
        None,
        alias="usedRange",
        description="O período (`range`) efetivamente utilizado para os dados históricos, se solicitado.",
    )
    historical_data_price: Optional[list[CryptoHistoricalData]] = Field(
        None,
        alias="historicalDataPrice",
        description="Array contendo a série histórica de preços, retornado se `range` ou `interval` forem especificados.",
    )
    valid_ranges: Optional[list[str]] = Field(
        None,
        alias="validRanges",
        description="Lista dos valores válidos para o parâmetro `range` nesta criptomoeda.",
    )
    valid_intervals: Optional[list[str]] = Field(
        None,
        alias="validIntervals",
        description="Lista dos valores válidos para o parâmetro `interval` nesta criptomoeda.",
    )


class CryptoResponse(BaseModel):
    coins: Optional[list[CryptoCoin]] = Field(
        None,
        description="Array contendo os resultados detalhados para cada criptomoeda solicitada.",
    )


class CryptoAvailableResponse(BaseModel):
    coins: Optional[list[str]] = Field(
        None,
        description="Lista de siglas (tickers) das criptomoedas disponíveis (ex: `BTC`, `ETH`, `LTC`).",
    )


class Currency(BaseModel):
    currency: Optional[str] = Field(
        None,
        description="Nome da moeda ou par de moedas suportado (ex: `Dólar Americano/Real Brasileiro`, `Euro/Real Brasileiro`). A sigla pode ser extraída deste nome ou consultada em documentação adicional.",
    )


class CurrencyAvailableResponse(BaseModel):
    currencies: Optional[list[Currency]] = Field(
        None,
        description="Lista de objetos, cada um contendo o nome de uma moeda fiduciária ou par suportado pela API.",
    )


class CurrencyQuote(BaseModel):
    from_currency: str = Field(
        ...,
        alias="fromCurrency",
        description="**Moeda de Origem:** Sigla da moeda base do par (ex: `USD` em `USD-BRL`).",
        example="USD",
    )
    to_currency: str = Field(
        ...,
        alias="toCurrency",
        description="**Moeda de Destino:** Sigla da moeda de cotação do par (ex: `BRL` em `USD-BRL`).",
        example="BRL",
    )
    name: str = Field(
        ...,
        description="**Nome do Par:** Nome descritivo do par de moedas (ex: `Dólar Americano/Real Brasileiro`).",
        example="Dólar Americano/Real Brasileiro",
    )
    high: str = Field(
        ...,
        description="**Máxima:** Preço mais alto atingido pelo par no período recente (geralmente diário). Formato String.",
        example="5.22",
    )
    low: str = Field(
        ...,
        description="**Mínima:** Preço mais baixo atingido pelo par no período recente (geralmente diário). Formato String.",
        example="5.162",
    )
    bid_variation: str = Field(
        ...,
        alias="bidVariation",
        description="**Variação Absoluta (Bid):** Mudança absoluta no preço de compra (bid) desde o último fechamento ou período de referência. Formato String.",
        example="0.0454",
    )
    percentage_change: str = Field(
        ...,
        alias="percentageChange",
        description="**Variação Percentual:** Mudança percentual no preço do par desde o último fechamento ou período de referência. Formato String.",
        example="0.88",
    )
    bid_price: str = Field(
        ...,
        alias="bidPrice",
        description="**Preço de Compra (Bid):** Preço atual pelo qual o mercado está disposto a comprar a moeda de origem (`fromCurrency`) pagando com a moeda de destino (`toCurrency`). Formato String.",
        example="5.2097",
    )
    ask_price: str = Field(
        ...,
        alias="askPrice",
        description="**Preço de Venda (Ask):** Preço atual pelo qual o mercado está disposto a vender a moeda de origem (`fromCurrency`) recebendo a moeda de destino (`toCurrency`). Formato String.",
        example="5.2127",
    )
    updated_at_timestamp: str = Field(
        ...,
        alias="updatedAtTimestamp",
        description="**Timestamp da Atualização:** Data e hora da última atualização da cotação, representada como um **timestamp UNIX** (string contendo o número de segundos desde 1970-01-01 UTC).",
        example="1696601423",
    )
    updated_at_date: str = Field(
        ...,
        alias="updatedAtDate",
        description="**Data da Atualização:** Data e hora da última atualização da cotação, formatada de forma legível (`YYYY-MM-DD HH:MM:SS`).",
        example="2023-10-06 11:10:23",
    )


class CurrencyResponse(BaseModel):
    currency: list[CurrencyQuote] = Field(
        ...,
        description="Array contendo os objetos `CurrencyQuote`, um para cada par de moeda válido solicitado no parâmetro `currency`.",
    )


class InflationEntry(BaseModel):
    date: Optional[str] = Field(
        None,
        description="Data da medição da inflação, no formato `DD/MM/YYYY`.",
        example="01/01/2023",
    )
    value: Optional[str] = Field(
        None,
        description="Valor do índice de inflação para a data especificada (formato string, pode conter `%` ou ser apenas numérico).",
        example="4.56",
    )
    epoch_date: Optional[int] = Field(
        None,
        alias="epochDate",
        description="Timestamp UNIX (número de segundos desde 1970-01-01 UTC) correspondente à `date`.",
        example=1672531199,
    )


class InflationResponse(BaseModel):
    inflation: Optional[list[InflationEntry]] = Field(
        None,
        description="Array contendo os registros históricos de inflação para o país e período solicitados.",
    )


class InflationAvailableResponse(BaseModel):
    countries: Optional[list[str]] = Field(
        None,
        description="Lista de nomes de países (em minúsculas) para os quais há dados de inflação disponíveis (ex: `brazil`, `usa`, `argentina`).",
    )


class PrimeRateEntry(BaseModel):
    date: Optional[str] = Field(
        None,
        description="Data do registro no formato DD/MM/YYYY.",
        example="01/01/2022",
    )
    value: Optional[str] = Field(
        None,
        description="Valor da taxa básica de juros (SELIC) para a data correspondente.",
        example="9.25",
    )
    epoch_date: Optional[int] = Field(
        None,
        alias="epochDate",
        description="Timestamp em milissegundos (formato epoch) correspondente à data do registro.",
        example=1640995200000,
    )


class PrimeRateResponse(BaseModel):
    prime_rate: Optional[list[PrimeRateEntry]] = Field(
        None,
        alias="prime-rate",
        description="Array contendo os registros históricos de taxa básica de juros (SELIC) para o país e período solicitados.",
    )


class PrimeRateAvailableResponse(BaseModel):
    countries: Optional[list[str]] = Field(
        None,
        description="Lista de países com dados de taxa básica de juros (SELIC) disponíveis para consulta.",
        example=["brazil", "united states", "european union"],
    )
